In [1]:
import numpy as np

In [9]:
x=np.array([1, 2, 3, 5])

In [10]:
x

array([1, 2, 3, 5])

In [8]:
N=3

# np.vander function returns the ouput array in the order of x^N-1 in the first column and x^N-2 in the 2nd column and so on

In [5]:
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

if N is not defined, default value of N shall be the length of the matrix

In [11]:
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])